spring.application.name=edusphere-discovery-server

# Sprint 0 Day 2 added
server.port=8761

# without this 2 some times it could act as Eureka client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false